import { JetBrains_Mono } from "next/font/google";
import { Shojumaru } from "next/font/google";
import "./globals.css";

// components
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import PreloaderTransition from "@/components/PreloaderTransition";

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetBrainsMono",
});
const shojumaru = Shojumaru({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-shojumaru",
});

export const metadata = {
  title: "Jim Alpez | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jetBrainsMono.variable} ${shojumaru.variable}`}>
        <Header />
        <PreloaderTransition/>
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
